
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// import "dotenv/config";
// import { defineConfig, env } from "prisma/config";

// export default defineConfig({
//   schema: "prisma/schema.prisma",
//   migrations: {
//     path: "prisma/migrations",
//   },
//   engine: "classic",
//   datasource: {
//     url: env("DATABASE_URL"),
//   },
// });
import "dotenv/config";
import { defineConfig } from "@prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  // 移除显式的 datasource 覆盖，让 Prisma 默认从 schema.prisma 读取 env("DATABASE_URL")
  // 这样能确保 Prisma 引擎直接读取系统环境变量
});